module.exports.userNames = {
  // '@RajeevMasand': 'RajeevMasand',
  '@narendramodi': '@narendramodi',
  '@SrBachchan': '@SrBachchan',
  '@iamsrk': '@iamsrk',
  // '@BeingSalmanKhan': '@BeingSalmanKhan',
  // '@akshaykumar': '@akshaykumar',
  '@imVkohli': '@imVkohli',
  '@PMOIndia': '@PMOIndia',
  '@sachin_rt': '@sachin_rt',
  '@iHrithik': '@iHrithik',
  '@deepikapadukone': '@deepikapadukone',
  '@katyperry': '@katyperry',
  // '@justinbieber': '@justinbieber',
  // '@rihanna': '@rihanna',
  // '@taylorswift13': '@taylorswift13',
  // '@Cristiano': '@Cristiano',
  // '@ladygaga': '@ladygaga',
  // '@TheEllenShow': '@TheEllenShow',
  // '@ArianaGrande': '@ArianaGrande',
  // '@jtimberlake': '@jtimberlake',
  '@KimKardashian': '@KimKardashian',
  '@cricbuzz': '@cricbuzz',
  '@sardanarohit': '@sardanarohit',
  '@RajatSharmaLive': '@RajatSharmaLive',
  '@Actor_Vivek': '@Actor_Vivek',
  '@sambitswaraj': '@sambitswaraj',
  '@Atlee_dir': '@Atlee_dir',
  '@rithvik_RD': '@rithvik_RD',
  '@StumblerVideos': '@StumblerVideos',
  '@MissMalini': '@MissMalini',
  '@SadhguruJV': '@SadhguruJV',
  '@AllIndiaBakchod': '@AllIndiaBakchod',
  '@DharmaMovies': '@DharmaMovies',
  '@yrf': '@yrf',
  '@one_by_two': '@one_by_two',
  '@Bhuvan_Bam': '@Bhuvan_Bam',
  '@SunburnFestival': '@SunburnFestival',
  '@TSeries': '@TSeries',
  '@EastIndiaComedy': '@EastIndiaComedy',
  '@BiggBoss': '@BiggBoss',
  '@SonyMusicSouth': '@SonyMusicSouth',
}